#!/bin/bash

## zsh
# install zsh files
for i in $( ls zsh ); do
  ln zsh/$i ~/.$i
done

## i3
# make sure directory exists
mkdir -p ~/.config/i3/

# install
ln i3/config.base ~/.config/i3/config.base
ln i3/blocks.conf ~/.i3blocks.conf
j4-make-config dwm

## .desktop files
mkdir -p ~/.local/share/applications/

for i in $( ls dot-desktop ); do
  ln dot-desktop/$i ~/.local/share/applications/$i
done

## nvim
ln nvim/nvimrc ~/.nvimrc

## Xresources
mkdir -p ~/.colors/
ln xresources/Xresources ~/.Xresources

ln xresources/base16-chalk.dark.256.xresources ~/.colors/base16-chalk.dark.256.xresources

## tmux
ln tmux/tmux.conf ~/.tmux.conf
