# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt inc_append_history share_history hist_ignore_dups nomatch notify hist_ignore_space
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/thimoteus/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
source /usr/share/zsh/scripts/zgen/zgen.zsh

if ! zgen saved; then
  echo "Creating a zgen save"

  zgen oh-my-zsh
  zgen oh-my-zsh themes/flazz

  zgen load sharat87/zsh-vim-mode
  zgen load caiogondim/bullet-train-oh-my-zsh-theme
  zgen load srijanshetty/node.plugin.zsh
  zgen load marzocchi/zsh-notify
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-history-substring-search

  zgen save
fi

bindkey -v
alias vim="nvim"

function list_all() {
    emulate -L zsh
    ls
}
chpwd_functions=(${chpwd_functions[@]} "list_all")

# Base16 Shell
BASE16_THEME="chalk"
BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_THEME.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# editor
export EDITOR='nvim'
