# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt inc_append_history share_history hist_ignore_dups nomatch notify hist_ignore_space correct
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/thimoteus/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
source /usr/share/zsh/scripts/zgen/zgen.zsh

if ! zgen saved; then
  echo "Creating a zgen save"

  zgen oh-my-zsh
  zgen oh-my-zsh themes/flazz

  zgen load sharat87/zsh-vim-mode
  zgen load caiogondim/bullet-train-oh-my-zsh-theme
  zgen load marzocchi/zsh-notify
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-history-substring-search

  zgen save
fi

# vim keybindings
bindkey -v

# because i'm used to typing vim
alias vim="nvim"

function list_all() {
    emulate -L zsh
    ls
}
chpwd_functions=(${chpwd_functions[@]} "list_all")

# Base16 Shell
BASE16_THEME="chalk"
BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_THEME.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# editor
export EDITOR='nvim'

# nvm
export NVM_DIR="/home/thimoteus/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# more aliases
alias DOITNOW="sudo"

# path
typeset -U path
path=(/usr/lib/hardening-wrapper/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/bin/ ~/.gem/ruby/2.2.0/bin/ ~/.cabal/bin/ /usr/bin/vendor_perl/)

# unregister broken GHC packages. Run this a few times to resolve dependency rot in installed packages.
# ghc-pkg-clean -f cabal/dev/packages*.conf also works.
function ghc-pkg-clean() {
  for p in `ghc-pkg check $* 2>&1  | grep problems | awk '{print $6}' | sed -e 's/:$//'`
  do
    echo unregistering $p; ghc-pkg $* unregister $p
  done
}
 
# remove all installed GHC/cabal packages, leaving ~/.cabal binaries and docs in place.
# When all else fails, use this to get out of dependency hell and start over.
function ghc-pkg-reset() {
  if [[ $(readlink -f /proc/$$/exe) =~ zsh ]]; then
    read 'ans?Erasing all your user ghc and cabal packages - are you sure (y/N)? '
  else # assume bash/bash compatible otherwise
    read -p 'Erasing all your user ghc and cabal packages - are you sure (y/N)? ' ans
  fi
 
  [[ x$ans =~ "xy" ]] && ( \
    echo 'erasing directories under ~/.ghc'; command rm -rf `find ~/.ghc/* -maxdepth 1 -type d`; \
    echo 'erasing ~/.cabal/lib'; command rm -rf ~/.cabal/lib; \
  )
}
 
alias cabalupgrades="cabal list --installed  | egrep -iv '(synopsis|homepage|license)'"
